<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|AnyCPU'">
    <OutputPath>..\Documents\Tools\TShock\ServerPlugins\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="9.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="OTAPI">
      <HintPath>C:\Users\benit\Documents\Proyectos\TerrapapusPro2026\TshockTEST\bin\OTAPI.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="TerrariaServer">
      <HintPath>C:\Users\benit\Documents\Proyectos\TerrapapusPro2026\TshockTEST\bin\TerrariaServer.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="TShockAPI">
      <HintPath>C:\Users\benit\Documents\Proyectos\TerrapapusPro2026\TshockTEST\ServerPlugins\TShockAPI.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

</Project>